function [time,activity,subject] = importActiwatch(filename, startRow, endRow)
%IMPORTACTIWATCH Import numeric data from a text file as column vectors.
%   [TIME,ACTIVITY,SUBJECT] = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   [TIME,ACTIVITY,SUBJECT] = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads
%   data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   [time,activity,subject] = importfile('01_3_21_2011_3_24_2011.csv',3,17560);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2013/08/07 15:01:08

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 3;
    endRow = inf;
end

%% Format string for each line of text:
%   column3: text (%s)
%	column4: text (%s)
%   column5: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*s%*s%s%s%f%*s%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1,...
    'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines',...
    startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec,...
        endRow(block)-startRow(block)+1, 'Delimiter', delimiter,...
        'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1,...
        'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Allocate imported array to column variable names
date0 = dataArray{:, 1};
time0 = dataArray{:, 2};
[currentYear,~,~,~,~,~] = datevec(now);
% Combine date and time
time1 = datenum(date0) + datenum(time0) - datenum(currentYear,1,1);
activity1 = dataArray{:, 3};

%% Extract information from filename
[~,name,~] = fileparts(filename);
pattern    = 'sub(\d*)_(\d*)-(\d*)-(\d*)_(\d*)-(\d*)-(\d*)';
tokens     = regexpi(name,pattern,'tokens');
numTokens  = str2double(tokens{1});
subject    = numTokens(1);
fileStart  = datenum(numTokens(2),numTokens(3),numTokens(4));
fileEnd    = datenum(numTokens(5),numTokens(6),numTokens(7));

%% Trim the data
idx1 = time1 >= fileStart & time1 < fileEnd + 1;
idx2 = isnan(activity1);
time = time1(idx1 & ~idx2);
activity = activity1(idx1 & ~idx2);

end
